//選取縣市
export const SET_CITY = "SET_CITY";

export const SET_ROUTE_Info = "SET_ROUTE_Info";

//設定選取路線
export const SET_ROUTE_ESTIMATEDTIME = "SET_ROUTE_ESTIMATEDTIME";

export const SET_STOP_ESTIMATEDTIME = "SET_STOP_ESTIMATEDTIME";

export const SET_BUS_ESTIMATEDTIME = "SET_BUS_ESTIMATEDTIME ";

export const SET_BUS_REALTIME = "SET_BUS_REALTIME";